[package]
name = "oxibus-tools"
description = "OxiBus CLI tools: dbus-send, dbus-monitor, dbus-launch, ..."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "dbus-send"
path = "src/bin/dbus-send.rs"

[[bin]]
name = "dbus-monitor"
path = "src/bin/dbus-monitor.rs"

[[bin]]
name = "dbus-launch"
path = "src/bin/dbus-launch.rs"

[[bin]]
name = "dbus-uuidgen"
path = "src/bin/dbus-uuidgen.rs"

[[bin]]
name = "dbus-cleanup-sockets"
path = "src/bin/dbus-cleanup-sockets.rs"

[[bin]]
name = "dbus-run-session"
path = "src/bin/dbus-run-session.rs"

[[bin]]
name = "dbus-update-activation-environment"
path = "src/bin/dbus-update-activation-environment.rs"

[dependencies]
oxibus-core = { workspace = true }
oxibus-client = { workspace = true }
oxibus-config = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
oxibus-auth = { workspace = true }
libc = { workspace = true }
