# OxiBus default security policy configuration.
# Path: /etc/oxibus/policy.d/00-default.toml

[[rule]]
context = "default"
allow_own = ["*"]
allow_send = ["*"]
allow_receive = ["*"]

[[rule]]
context = "mandatory"
deny_own = ["org.freedesktop.DBus"]

[[rule]]
context = "user"
user = "messagebus"
allow_own = ["org.freedesktop.DBus"]
