[package]
name = "oxibus-client"
description = "OxiBus connection, proxies and object server (the new libdbus)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
oxibus-core = { workspace = true }
oxibus-transport = { workspace = true }
oxibus-auth = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
once_cell = { workspace = true }

[lib]
name = "oxibus_client"
path = "src/lib.rs"
